services:

  postgres:
    container_name: webhook-endpoint-postgres
    image: postgres:16
    environment:
      POSTGRES_USER: endpoint
      POSTGRES_PASSWORD: endpoint
      POSTGRES_DB: endpoint
    networks:
      - endpoint
    volumes:
      - postgres_data:/var/lib/postgresql/data

  endpoint-app:
    container_name: endpoint-app
    build: .
    volumes:
      - ./:/srv/EndPointWebhook
    ports:
      - "8080:8080"
    command: /bin/bash
    stdin_open: true
    tty: true
    networks:
      - endpoint
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  endpoint:
    driver: bridge
